name: Dataform CI
on:
  pull_request:
    branches: [ main ]
jobs:
  dataform_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dataform CLI
        run: npm install -g @dataform/cli

      - name: Compile Dataform project
        run: dataform compile
