name: Dataform Production
on:
  push:
    branches: [ main ]
jobs:
  dataform_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dataform CLI
        run: npm install -g @dataform/cli

      - name: Create Dataform credentials file
        run: |
          echo '{"projectId":"ecommerce-analytics-dataform","location":"US"}' > .df-credentials.json

      - name: Run Dataform
        run: dataform run --project-dir .
